---
title: "Clase 3 actividad markdown"
author: "Jose Luis"
date: "June 2, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

ls("package:nycflights13")

#?flights
airlines_data <- airlines
airports_data <- airports
flights_data <- flights
planes_data <- planes
weather_data <- weather
# Variables in flights dataset
```{r}
ls("package:nycflights13")

#?flights
airlines_data <- airlines
airports_data <- airports
flights_data <- flights
planes_data <- planes
weather_data <- weather
# Variables in flights dataset
glimpse (flights)
glimpse (weather)
```

```{r}
library (nycflights13)
library(tidyverse)
library(patchwork)
g <- ggplot(flights, aes(distance)) #+ scale_fill_brewer(palette = "Spectral")

 

g + geom_histogram(binwidth = 100, 
                  col="black", 
                  size=.1) +  # change binwidth
  labs(title="Histogram with Auto Binning", 
       subtitle="Engine Displacement across Vehicle Classes")
```
```{r}
ggplot(weather_data, aes(x = temp)) +
  geom_histogram(binwidth = 3, color = "grey", fill = "red", alpha= 0.5) +
  labs(x = "Temperature (degrees F)", y = "Count",
       title = "New York City Airport Temperatures 2013")
```
```{r}
ggplot(weather_data, aes(x = temp)) +
  geom_histogram(binwidth = 3, color = "grey", aes(fill = factor(month)), alpha= 0.5) +
  labs(x = "Temperature (degrees F)", y = "Count",
       title = "New York City Airport Temperatures 2013")
```
```{r}
glimpse (airports)
```
```{r}
g <- ggplot(airports, aes(lat))
g + geom_density(aes(fill=factor(tzone)), alpha=0.5) +
    labs(title="Density plot",
         subtitle="Latitudes of airports grouped by Time Zone",
         caption="Source: mpg",
         x="Latitude",
         fill="# Airports")
```
```{r}
g <- ggplot(airports, aes(lat, tzone))
g + geom_boxplot(varwidth=T, fill="dodgerblue", alpha = 0.5) +
    labs(title="Box plot",
         subtitle="Latitudes of airports grouped by Time Zone",
         caption="Source: mpg",
         x="Latitude",
         y="Time ZOne")

 #Setting varwidth=T adjusts the width of the boxes to be proportional to the number of observation it contains.
```
```{r}
g <- ggplot(airports, aes(lat, tzone))
g + geom_boxplot(aes(fill=factor(tzone))) +  scale_fill_brewer(palette = "Spectral") +
  theme(axis.text.x = element_text(angle=65, vjust=0.6)) +
  labs(title="Box plot",
       subtitle="Latitudes of airports grouped by Time Zone",
       caption="Source: mpg",
       x="Latitude",
       y="Time Zone")
```
```{r}
#Para la distribución de probabilidad
g <- ggplot(airports, aes(lat, tzone))
g + geom_violin() +
  labs(title="Violin plot",
       subtitle="Latitudes of airports grouped by Time Zone",
       caption="Source: mpg",
       x="Latitude",
       y="Time Zoe")
```

```
